import { render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe,it,expect,vi } from 'vitest';
import App,{ChatMessageRenderer,LeadForm,LeadScoreCard} from './main';

describe('ChatMessageRenderer',()=>{it.each([['pending','Thinking…'],['streaming','Writing response…'],['error','Error: Network unavailable']])('renders %s state', (state,text)=>{render(<ChatMessageRenderer message={{state,content:'Network unavailable'}}/>);expect(screen.getByRole('status')).toHaveTextContent(text)});it('renders completed and tool result states',()=>{render(<><ChatMessageRenderer message={{state:'completed',content:'Done'}}/><ChatMessageRenderer message={{state:'tool',content:'42'}}/></>);expect(screen.getByText('Done')).toBeInTheDocument();expect(screen.getByText('Tool result: 42')).toBeInTheDocument()})});
describe('LeadForm',()=>{it('validates required company name',async()=>{const user=userEvent.setup();render(<LeadForm onSubmit={vi.fn()}/>);await user.click(screen.getByRole('button',{name:'Score lead'}));expect(screen.getByRole('alert')).toHaveTextContent('Company name is required')});it('submits a valid lead',async()=>{const user=userEvent.setup(),onSubmit=vi.fn();render(<LeadForm onSubmit={onSubmit}/>);await user.type(screen.getByLabelText('Company name'),'Acme');await user.selectOptions(screen.getByLabelText('Company size'),'medium');await user.selectOptions(screen.getByLabelText('Buying intent'),'ready');await user.click(screen.getByRole('button',{name:'Score lead'}));expect(onSubmit).toHaveBeenCalledWith({company:'Acme',size:'medium',intent:'ready'})})});
describe('LeadScoreCard',()=>{it('renders score, tier, action, and reasons',()=>{render(<LeadScoreCard result={{score:91,tier:'Hot',action:'Call today',reasons:['Large company','High intent']}}/>);expect(screen.getByText('91')).toBeInTheDocument();expect(screen.getByText('Hot')).toBeInTheDocument();expect(screen.getByText('Call today')).toBeInTheDocument();expect(screen.getByText('Large company')).toBeInTheDocument()})});
describe('App API flow',()=>{it('shows loading then mocked success result',async()=>{const user=userEvent.setup();render(<App/>);await user.type(screen.getByLabelText('Company name'),'Acme');await user.click(screen.getByRole('button',{name:'Score lead'}));expect(screen.getByText('Loading score…')).toBeInTheDocument();expect(await screen.findByRole('heading',{name:'Lead score'})).toBeInTheDocument();expect(screen.getByText('Hot')).toBeInTheDocument()});it('shows mocked API error result',async()=>{const user=userEvent.setup(),api=vi.fn().mockRejectedValue(new Error('API unavailable'));render(<App api={api}/>);await user.type(screen.getByLabelText('Company name'),'Error Co');await user.click(screen.getByRole('button',{name:'Score lead'}));expect(await screen.findByRole('alert')).toHaveTextContent('Unable to score this lead');expect(api).toHaveBeenCalled()})});
